### PR TITLE
V0.2

### PR DESCRIPTION
**Pull request by hotmeteor**
v0.2 makes a lot of changes and updates:

- Converts the project to use [Laravel Zero](https://laravel-zero.com/)
- Adds Gitlab and Bitbucket drivers
- All commands are tested 🎉 
- Lots of clean ups

There are a few breaking changes:

1. The `env:pull` command is now called `env:sync`
2. Vault values are now namespaced by `org` and `repo` instead of just the `local` namespace

### CODE REVIEW

**Comment by ghost** [comment]
@hotmeteor when running composer global require hotmeteor/eco-cli:v0.2.x-dev on windows this error is displayed:
``` 
Problem 1
    - php-school/cli-menu 4.0.0 requires ext-posix * -> the requested PHP extension posix is missing from your system.
    - hotmeteor/eco-cli v0.2.x-dev requires nunomaduro/laravel-console-menu ^3.1 -> satisfiable by nunomaduro/laravel-console-menu[v3.1.0].
    - nunomaduro/laravel-console-menu v3.1.0 requires php-school/cli-menu ^4.0 -> satisfiable by php-school/cli-menu[4.0.0].
    - Installation request for hotmeteor/eco-cli v0.2.x-dev -> satisfiable by hotmeteor/eco-cli[v0.2.x-dev].
```
This would be an easy fix but according to https://www.php.net/manual/en/intro.posix.php this extension isn't available for php on windows platforms

**Comment by hotmeteor** [comment]
@cole-flexsim Removed

**Comment by hotmeteor** [comment]
@cole-flexsim If you want to wait a couple days for me to test out Gitlab that's fine. I'm starting on it now.

**Comment by hotmeteor** [comment]
@cole-flexsim I believe the Gitlab provider should work now. If you want to try it, here's what you need to do:

1. Create a Personal Access Token: https://gitlab.com/profile/personal_access_tokens
    - Choose `api` privileges
2. Create a Deploy Key for your project: https://gitlab.com/[group]/[project]/-/settings/repository
    - Name it `eco-cli`
    - Make sure "Write access allowed" is checked
3. Run `eco init`, choose `gitlab`, and enter your token.

That should be it!

**Pull request merged**
